### ISSUE TITLE
Jekyll server failed for doc with "`/' not found." in Browser

### ISSUE THREAD

**Issue by christophwolff** [band-x-media/SASS-Material-Design-for-Bootstrap#7]
If i install via npm and want to build via grunt, the server started but cant find the URL.
Displays `/' not found. in the Browser. 

Solution is to delete the complete line from the jekyll server config. (_config.yml)
baseurl: "/SASS-Material-Design-for-Bootstrap"

**Comment by andrew-waters** [comment]
This is currently configured this way because we have a Travis build which pushes updates to the gh-pages branch which this repo is one of a number of hosted ones. I'll rewrite it at some point soon to use the empty URI and publish to a subfolder instead. Like you say, updating the config helps or you can navigate to the local URL: http://127.0.0.1:4000/SASS-Material-Design-for-Bootstrap/

**Comment by christophwolff** [comment]
ok. I thought so. Thanks!

BTW Best Material Design Bootstrap implimentation on Github! Srsly i tested them all ... But you really need to provide some examples to get startet :)
Please keep up the good work!

**Comment by andrew-waters** [comment]
Thanks Christoph, glad to hear you're enjoying it :-)
Examples are definitely on the way, probably as a few different layout templates to get you started...

**Comment by christophwolff** [comment]
Sounds great! Thank you!
